In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel('Covid_Data_new.xlsx')

In [25]:
df.head(10)

age body_temperature chronic_disease breathing_issue  \
0  10.0           Normal              no              no   
1  12.0           Normal              no              no   
2  15.0           Normal              no              no   
3  10.0           Normal              no              no   
4  13.0         Moderate              no              no   
5  12.0         Moderate              no              no   
6  13.0         Moderate              no              no   
7  15.0         Moderate              no              no   
8  18.0         Moderate              no              no   
9  19.0           Normal              no              no   

   Blood O2 Level in Percentage Needed Hospitalization  
0                          97.0                     No  
1                          97.0                     No  
2                          94.0                     No  
3                          97.0                     No  
4                          94.0                     No  
5                          97.0                     No  
6                          93.0                     No  
7                          92.0                     No  
8                          66.0                    Yes  
9                          92.0                     No

In [13]:
x = df.iloc[:, :-1].values
x

array([[10.0, 'Normal', 'no', 'no', 97.0],
       [12.0, 'Normal', 'no', 'no', 97.0],
       [15.0, 'Normal', 'no', 'no', 94.0],
       [10.0, 'Normal', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 94.0],
       [12.0, 'Moderate', 'no', 'no', 97.0],
       [13.0, 'Moderate', 'no', 'no', 93.0],
       [15.0, 'Moderate', 'no', 'no', 92.0],
       [18.0, 'Moderate', 'no', 'no', 66.0],
       [19.0, 'Normal', 'no', 'no', 92.0],
       [20.0, 'Normal', 'no', 'no', 93.0],
       [17.0, 'Normal', 'no', 'no', 93.0],
       [16.0, 'Normal', 'no', 'no', 92.0],
       [18.0, 'Normal', 'no', 'no', 93.0],
       [20.0, 'Normal', 'no', 'no', 92.0],
       [25.0, 'Moderate', 'no', 'no', 93.0],
       [24.0, 'Moderate', 'no', 'no', 92.0],
       [26.0, 'High', 'no', 'no', 94.0],
       [28.0, 'Normal', 'no', 'no', 99.0],
       [29.0, 'Normal', 'no', 'no', 93.0],
       [30.0, 'Moderate', 'no', 'no', 62.0],
       [19.0, 'Normal', 'no', 'no', 89.0],
       [25.0, 'Normal', 'no', 'yes', 86.

In [29]:
y = df.iloc[:, -1].values
y

array(['No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
       'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
       'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes'],
      dtype=object)

In [16]:
from sklearn.impute import SimpleImputer

## Handling Missing Data

In [26]:
imputer = SimpleImputer(missing_values= np.nan,strategy='mean')
imputer.fit(x[:, 0:1])
x[: , 0:1] = imputer.transform(x[:, 0:1])
x

array([[1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [1.0, 0.0, 0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [1.0, 0.0, 0.0, 1.0, 15.0, 'no', 'no', 94.0],
       [1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 94.0],
       [0.0, 1.0, 0.0, 0.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 0.0, 15.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 18.0, 'no', 'no', 66.0],
       [1.0, 0.0, 0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 17.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 18.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 25.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 0.0, 24.0, 'no', 'no', 92.0],
       [1.0, 0.0, 1.0, 0.0, 26.0, 'no', 'no', 94.0],
       [1.0, 0.0, 0.0, 1.0, 28.0, 'no', 'no', 

## Encoding Categorical Value

## Encoding Independent Variable 

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [24]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

array([[1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [1.0, 0.0, 0.0, 1.0, 12.0, 'no', 'no', 97.0],
       [1.0, 0.0, 0.0, 1.0, 15.0, 'no', 'no', 94.0],
       [1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 94.0],
       [0.0, 1.0, 0.0, 0.0, 12.0, 'no', 'no', 97.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 0.0, 15.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 18.0, 'no', 'no', 66.0],
       [1.0, 0.0, 0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 17.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 18.0, 'no', 'no', 93.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 25.0, 'no', 'no', 93.0],
       [0.0, 1.0, 0.0, 0.0, 24.0, 'no', 'no', 92.0],
       [1.0, 0.0, 1.0, 0.0, 26.0, 'no', 'no', 94.0],
       [1.0, 0.0, 0.0, 1.0, 28.0, 'no', 'no', 

## Encoding Dependent Variable

In [31]:
from sklearn.preprocessing import LabelEncoder
dep = LabelEncoder()
y = dep.fit_transform(y)

## Splitting Training and Testing Set

In [32]:
 from sklearn.model_selection import train_test_split

In [34]:
#spliting entire data sets into training set and Testing Set
#testing set has 20% (Test_size = 0.2)
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

##Variable X has Independent Value and Variable Y has Dependent Value

In [35]:
X_train

array([[1.0, 0.0, 1.0, 0.0, 86.0, 'yes', 'yes', 71.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 'no', 'yes', 92.0],
       [1.0, 0.0, 1.0, 0.0, 75.0, 'no', 'yes', 72.0],
       [1.0, 0.0, 1.0, 0.0, 42.0, 'no', 'no', 92.0],
       [1.0, 0.0, 1.0, 0.0, 74.0, 'yes', 'yes', 75.0],
       [1.0, 0.0, 1.0, 0.0, 62.0, 'yes', 'yes', 68.0],
       [0.0, 1.0, 0.0, 0.0, 24.0, 'no', 'no', 92.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 'no', 'yes', 93.0],
       [1.0, 0.0, 1.0, 0.0, 58.0, 'no', 'no', 70.0],
       [0.0, 1.0, 0.0, 0.0, 45.130434782608695, 'yes', 'no', 90.0],
       [0.0, 1.0, 0.0, 0.0, 15.0, 'no', 'no', 92.0],
       [1.0, 0.0, 0.0, 1.0, 70.0, 'no', 'yes', 88.0],
       [1.0, 0.0, 1.0, 0.0, 52.0, 'yes', 'yes', 80.0],
       [1.0, 0.0, 1.0, 0.0, 60.0, 'yes', 'yes', 68.0],
       [1.0, 0.0, 1.0, 0.0, 54.0, 'yes', 'yes', 70.0],
       [1.0, 0.0, 0.0, 1.0, 29.0, 'no', 'no', 93.0],
       [1.0, 0.0, 1.0, 0.0, 78.0, 'yes', 'yes', 71.0],
       [1.0, 0.0, 1.0, 0.0, 36.0, 'yes', 'no', 90.0],
       [0.0,

In [36]:
X_test

array([[1.0, 0.0, 0.0, 1.0, 25.0, 'no', 'yes', 86.0],
       [1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 97.0],
       [1.0, 0.0, 1.0, 0.0, 68.0, 'yes', 'no', 67.0],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 94.0],
       [1.0, 0.0, 1.0, 0.0, 59.0, 'yes', 'no', 68.0],
       [1.0, 0.0, 0.0, 1.0, 28.0, 'no', 'no', 99.0],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 93.0],
       [1.0, 0.0, 1.0, 0.0, 46.0, 'yes', 'no', 91.0],
       [1.0, 0.0, 1.0, 0.0, 53.0, 'yes', 'no', 55.0],
       [1.0, 0.0, 0.0, 1.0, 16.0, 'no', 'no', 92.0],
       [1.0, 0.0, 1.0, 0.0, 38.0, 'no', 'no', 75.0],
       [1.0, 0.0, 0.0, 1.0, 19.0, 'no', 'no', 92.0],
       [1.0, 0.0, 1.0, 0.0, 94.0, 'yes', 'yes', 64.0],
       [0.0, 1.0, 0.0, 0.0, 12.0, 'no', 'no', 97.0]], dtype=object)

In [37]:
y_test

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [38]:
y_train

array([1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1])

## Feature Scaling 
### Feature Scaling is a technique to standardized the independent features to present data  in fixed range

In [39]:
from sklearn.preprocessing import StandardScaler

In [44]:
fs = StandardScaler()
X_train[:,7:]= fs.fit_transform(X_train[:,7:])
X_test[:,7:]= fs.fit_transform(X_test[:,7:])

In [45]:
X_train

array([[1.0, 0.0, 1.0, 0.0, 86.0, 'yes', 'yes', -0.9846525343745063],
       [0.0, 1.0, 0.0, 0.0, 35.0, 'no', 'yes', 0.9494863724325597],
       [1.0, 0.0, 1.0, 0.0, 75.0, 'no', 'yes', -0.8925506816694079],
       [1.0, 0.0, 1.0, 0.0, 42.0, 'no', 'no', 0.9494863724325597],
       [1.0, 0.0, 1.0, 0.0, 74.0, 'yes', 'yes', -0.6162451235541128],
       [1.0, 0.0, 1.0, 0.0, 62.0, 'yes', 'yes', -1.2609580924898016],
       [0.0, 1.0, 0.0, 0.0, 24.0, 'no', 'no', 0.9494863724325597],
       [0.0, 1.0, 0.0, 0.0, 48.0, 'no', 'yes', 1.0415882251376583],
       [1.0, 0.0, 1.0, 0.0, 58.0, 'no', 'no', -1.0767543870796048],
       [0.0, 1.0, 0.0, 0.0, 45.130434782608695, 'yes', 'no',
        0.765282667022363],
       [0.0, 1.0, 0.0, 0.0, 15.0, 'no', 'no', 0.9494863724325597],
       [1.0, 0.0, 0.0, 1.0, 70.0, 'no', 'yes', 0.5810789616121663],
       [1.0, 0.0, 1.0, 0.0, 52.0, 'yes', 'yes', -0.15573586002862091],
       [1.0, 0.0, 1.0, 0.0, 60.0, 'yes', 'yes', -1.2609580924898016],
       [1.0, 0.0, 

In [46]:
X_test

array([[1.0, 0.0, 0.0, 1.0, 25.0, 'no', 'yes', 0.17205102992570073],
       [1.0, 0.0, 0.0, 1.0, 10.0, 'no', 'no', 0.9513409890009328],
       [1.0, 0.0, 1.0, 0.0, 68.0, 'yes', 'no', -1.1739952630224273],
       [0.0, 1.0, 0.0, 0.0, 13.0, 'no', 'no', 0.7388073637985968],
       [1.0, 0.0, 1.0, 0.0, 59.0, 'yes', 'no', -1.1031507212883154],
       [1.0, 0.0, 0.0, 1.0, 28.0, 'no', 'no', 1.0930300724691568],
       [1.0, 0.0, 0.0, 1.0, 20.0, 'no', 'no', 0.6679628220644848],
       [1.0, 0.0, 1.0, 0.0, 46.0, 'yes', 'no', 0.5262737385962607],
       [1.0, 0.0, 1.0, 0.0, 53.0, 'yes', 'no', -2.0241297638317715],
       [1.0, 0.0, 0.0, 1.0, 16.0, 'no', 'no', 0.5971182803303727],
       [1.0, 0.0, 1.0, 0.0, 38.0, 'no', 'no', -0.6072389291495313],
       [1.0, 0.0, 0.0, 1.0, 19.0, 'no', 'no', 0.5971182803303727],
       [1.0, 0.0, 1.0, 0.0, 94.0, 'yes', 'yes', -1.3865288882247633],
       [0.0, 1.0, 0.0, 0.0, 12.0, 'no', 'no', 0.9513409890009328]],
      dtype=object)